plugins {
    // Kita langsung sematkan versi plugin '8.2.2' di sini agar server GitHub Actions tidak bingung mencari versinya
    id 'com.android.application' version '8.2.2'
    id 'org.jetbrains.kotlin.android' version '1.9.22'
}

android {
    namespace 'com.proyek.multicloner'
    compileSdk 34

    defaultConfig {
        applicationId "com.proyek.multicloner"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    
    // Menggunakan tag rilis repositori publik yang valid di Jitpack
    implementation 'com.github.ALEX5402:NewBlackbox:v1.0.2'
}
